sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t wltsankalpa/simple-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true wltsankalpa/simple-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'simple-react-app'
  env: 'react-app-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-153396620132'
  bucket_path: 'simple-react-app'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
